import type { ExtensionThemeConfig, HunkExtensionAPI } from "hunkdiff/extension";

/** The final built-in Graphite palette from before Hunk switched to bundled themes. */
export const GRAPHITE_THEME = {
  id: "graphite",
  label: "Graphite",
  base: "github-dark-default",
  background: "#111315",
  panel: "#171a1d",
  panelAlt: "#1d2126",
  border: "#343c45",
  accent: "#d5e0ea",
  accentMuted: "#414a54",
  text: "#f2f4f6",
  muted: "#9aa4af",
  addedBg: "#1f3025",
  removedBg: "#372526",
  movedAddedBg: "#1d3140",
  movedRemovedBg: "#34283d",
  contextBg: "#181c20",
  addedContentBg: "#24362a",
  removedContentBg: "#432b2d",
  contextContentBg: "#1e2328",
  addedSignColor: "#88d39b",
  removedSignColor: "#f0a0a0",
  lineNumberBg: "#14181b",
  lineNumberFg: "#798592",
  selectedHunk: "#4f5d6b",
  badgeAdded: "#88d39b",
  badgeRemoved: "#f0a0a0",
  badgeNeutral: "#a9b4bf",
  fileNew: "#88d39b",
  fileDeleted: "#f0a0a0",
  fileRenamed: "#e6cf98",
  fileModified: "#c49bff",
  fileUntracked: "#7fd1ff",
  noteBorder: "#c6a0ff",
  noteBackground: "#241c31",
  noteTitleBackground: "#322446",
  noteTitleText: "#f5edff",
  syntaxScopes: {
    source: "#f2f4f6",
    keyword: "#c49bff",
    string: "#9bd8a9",
    comment: "#9aa4af",
    "punctuation.definition.comment": "#9aa4af",
    "constant.numeric": "#e6cf98",
    "entity.name.function": "#7fd1ff",
    "support.function": "#7fd1ff",
    "variable.function": "#7fd1ff",
    "variable.other.property": "#a8c8ff",
    "support.variable.property": "#a8c8ff",
    "entity.name.type": "#ffd08a",
    "entity.name.class": "#ffd08a",
    "support.type": "#ffd08a",
    "support.class": "#ffd08a",
    variable: "#f2f4f6",
    "keyword.operator": "#89dceb",
    punctuation: "#a9b4bf",
  },
} as const satisfies ExtensionThemeConfig;

export default function registerGraphiteTheme(hunk: Pick<HunkExtensionAPI, "registerTheme">) {
  hunk.registerTheme(GRAPHITE_THEME);
}
